export const DEFAULT_ROLE_PERMISSIONS = {
  OWNER: [
    'MANAGE_RESTAURANT',
    'MANAGE_STAFF',
    'MANAGE_MENU',
    'MANAGE_RESERVATIONS',
    'VIEW_REPORTS',
    'BASIC_OPERATIONS'
  ],
  MANAGER: [
    'MANAGE_MENU',
    'MANAGE_RESERVATIONS',
    'VIEW_REPORTS',
    'BASIC_OPERATIONS'
  ],
  STAFF: [
    'BASIC_OPERATIONS'
  ]
} as const; 