# Server Configuration
server:
  port: 3000
  host: "localhost"
  apiPrefix: "/api/v1"

# Authentication
auth:
  jwt:
    token: ${JWT_SECRET}
    expiresIn: "24h"
    cookieMaxAge: 604800000 # 7 days in milliseconds
  google:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
    callbackURL: "/api/v1/auth/google/callback"

# Database Configuration
database:
  postgres:
    url: ${DATABASE_URL}
    host: ${DB_HOST}
    port: ${DB_PORT}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    database: ${DB_NAME}
  redis:
    url: ${REDIS_URL}
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

# Email Configuration
email:
  smtp:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    secure: true
    auth:
      user: ${SMTP_USER}
      pass: ${SMTP_PASSWORD}
  sender:
    name: "Your App Name"
    email: ${SMTP_FROM_EMAIL}

# Verification Configuration
verification:
  codeExpirationTime: 300000 # 5 minutes in milliseconds

# Cors Configuration
cors:
  origin: ${CORS_ORIGIN}
  credentials: true

# Cache Configuration
cache:
  ttl: 3600 # 1 hour in seconds
