app:
  name: "TableGo API"
  environment: "development"
  port: 3000
  host: "localhost"
  apiPrefix: "/api/v1"

env:
  host: "development"

verification:
  codeExpirationTime: 300

mail:
  smtp:
    server: "smtp.gmail.com"
    port: 465

cors:
  allowedOrigins:
    - "http://localhost:3000"
    - "http://localhost:3001"
  allowedMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "PATCH"

rateLimit:
  windowMs: 900000  
  maxRequests: 100
