name: Deploy to Development

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: Deploy to server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "rm -rf ${{ secrets.PROJECT_PATH }} && \
          mkdir -p ${{ secrets.PROJECT_PATH }} && \
          cd ${{ secrets.PROJECT_PATH }} && \
          git clone git@github.com:compera-digital/business-tablego-backend.git . && \
          git config --global user.email 'github-actions@github.com' && \
          git config --global user.name 'GitHub Actions' && \
          git checkout main && \
          yarn install && \
          docker compose down && \
          docker compose up -d && \
          /usr/local/bin/npx prisma migrate deploy && \
          sudo systemctl restart business-tablego-backend.service"
